version: '3.8'

services:
    backend:
        build: .
        command: python main.py
        ports:
            - "8000:80"
        env_file:
            - .env
        volumes:
            - ./yourscript/infrastructure/db/migrations/versions:/home/app/yourscript/infrastructure/db/migrations/versions
        depends_on:
            - db

    db:
        image: postgres:14.5-alpine
        volumes:
            - backend_pg_data:/var/lib/postgresql/data/
        env_file:
            - .env

volumes:
    backend_pg_data: