version: '3.8'

services:
    backend:
        build: .
        command: python src/yourscript/main/web.py
        ports:
            - "8000:80"
        env_file:
            - .env
        volumes:
            - ./src/yourscript/infrastructure/db/migrations/versions:/home/app/src/yourscript/infrastructure/db/migrations/versions
        depends_on:
            - db

    db:
        image: postgres:14.5-alpine
        volumes:
            - backend_pg_data:/var/lib/postgresql/data/
        env_file:
            - .env

    migration:
        build: .
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - db
            - backend
        command: [ "python", "-m", "alembic", "upgrade", "head" ]

volumes:
    backend_pg_data: