services:
    web:
        image: nginx:1.25.5-alpine
        ports:
            - 80:80
        depends_on:
            - backend
        volumes:
            - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf

    backend:
        container_name: backend
        restart: on-failure
        build: .
        command: fastapi run src/zametka/main/web.py --root-path=/api/
        env_file:
            - .env.access_service
            - .env.notes
            - .env
        volumes:
            - ./src/zametka/access_service/infrastructure/persistence/alembic/migrations/versions:/home/app/backend/src/zametka/access_service/infrastructure/persistence/alembic/migrations/versions
            - ./src/zametka/notes/infrastructure/persistence/alembic/migrations/versions:/home/app/backend/src/zametka/notes/infrastructure/persistence/alembic/migrations/versions
            - ./.config/dev.config.toml:/usr/local/etc/zametka/cfg.toml
        depends_on:
            - migration
    db:
        container_name: persistence
        image: zametkaru/postgres-multi-db
        volumes:
            - pg_data:/var/lib/postgresql/data/
        env_file:
            - .env
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d access_database -U $${POSTGRES_USER}",
                    "CMD-SHELL", "pg_isready -d notes_database -U $${POSTGRES_USER}" ]
            interval: 2s
            timeout: 60s
            retries: 10
            start_period: 3s

    migration:
        container_name: migration
        build: .
        restart: on-failure
        env_file:
            - .env.access_service
            - .env
            - .env.notes
        depends_on:
            db:
                condition: service_healthy
        command: [ "zametka", "all", "alembic", "upgrade", "head" ]

volumes:
    pg_data:
