from zametka.access_service.domain.exceptions.base import DomainError


class UserIsNotActiveError(DomainError): ...


class InvalidCredentialsError(DomainError): ...


class WeakPasswordError(DomainError): ...


class InvalidUserEmailError(DomainError): ...
